apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-k8s-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
     app: sample-k8s-deployment
  template:
    metadata:
      labels:
        app: sample-k8s-deployment
    spec:
      containers:
      - name: sample-k8s-app-container
        image: kowsylakshu/webapplication:v1
        ports:
        - containerPort: 8080
      imagePullSecrets: ifNotPresent
